trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'AKSVariableGroup'
  
stages:
  - stage: DeployAKSCluster
    displayName: 'Deploy AKS Cluster'
    jobs:
      - job: Deploy
        displayName: 'Deploy AKS Cluster to Azure'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Creating Resource Group..."
                az group create --name $(resourceGroup) --location $(location)
                
                echo "Creating Virtual Network..."
                az network vnet create --resource-group $(resourceGroup) --name $(vnetName) --address-prefix 10.0.0.0/16 --location $(location)
                
                echo "Creating Subnet..."
                az network vnet subnet create --resource-group $(resourceGroup) --vnet-name $(vnetName) --name $(subnetName) --address-prefix 10.0.0.0/24

                echo "Creating AKS Cluster..."
                az aks create --resource-group $(resourceGroup) --name $(aksClusterName) --node-count 3 --enable-addons monitoring --generate-ssh-keys --vnet-subnet-id $(az network vnet subnet show --resource-group $(resourceGroup) --vnet-name $(vnetName) --name $(subnetName) --query id -o tsv)

                echo "AKS Cluster deployed successfully"
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Getting AKS credentials..."
                az aks get-credentials --resource-group $(resourceGroup) --name $(aksClusterName)

                echo "Verifying AKS Cluster..."
                kubectl get nodes
